services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs-t1-backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Ensure that node_modules are not overwritten by the host
    networks:
      - cs_t1_construcao
    env_file:
      - .env

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: cs-t1-database
    ports:
      - "5432:5432"
    volumes:
      - ./database/dumps:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cs-t1
    networks:
      - cs_t1_construcao
    env_file:
      - .env

networks:
  cs_t1_construcao:
    driver: bridge
